name: RSpec Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:
    secrets:
      CC_TEST_REPORTER_ID:
        description: 'Code Climate Reporter ID for current repo'
        required: false
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: amancevice/setup-code-climate@v0
        name: CodeClimate Install
        with:
          cc_test_reporter_id: ${{ secrets.CC_TEST_REPORTER_ID }}
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: CodeClimate Pre-build Notification
        run: cc-test-reporter before-build
      # Add or replace test runners here
      - name: Run RSpec
        run: bundle exec rspec spec/
      - name: CodeClimate Post-build Notification
        run: cc-test-reporter after-build -t simplecov -r ${{secrets.CC_TEST_REPORTER_ID}}
