name: Rubocop
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [ opened, reopened, synchronize, ready_for_review ]

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: bundle install
      - name: Rubocop
        run: bundle exec rubocop